#!/usr/bin/env node
/**
 * Scans public/models/Charecters/ and generates src/data/generatedCharacters.js
 * with CHARACTER_CONFIGS, NPC_PLACEMENTS, and NPC_GROUPS for all downloaded characters.
 *
 * Usage: node scripts/generateCharacterConfigs.js
 */

const fs = require('fs')
const path = require('path')

const CHARS_DIR = path.join(__dirname, '..', 'public', 'models', 'Charecters')
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'data', 'generatedCharacters.js')

// Hall bounds for NPC placement
const HALL_X = [-12.6, 12.6]
const HALL_Z = [-49, 49]

// Max characters to include (pick first N alphabetically)
const MAX_CHARACTERS = 5

// Animation filename fuzzy mapping
const ANIM_MAP = {
  walk: ['Walking.fbx', 'Strut Walking.fbx', 'Mutant Walking.fbx'],
  run: ['Running.fbx', 'Slow Run.fbx'],
  jump: ['Jumping.fbx', 'Mutant Jumping.fbx', 'Jumping (1).fbx'],
}

// Known height overrides
const HEIGHT_OVERRIDES = {
  'Mutant': 3.0,
  'The Boss': 2.2,
  'Vanguard': 2.0,
  'Big Vegas': 2.1,
  'Alpha': 2.0,
  'Brute': 2.5,
  'Goblin D Shareyko': 1.2,
}

function sanitizeKey(folderName) {
  return folderName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
}

function findAnim(files, candidates) {
  for (const candidate of candidates) {
    if (files.includes(candidate)) return candidate
  }
  return null
}

function generateConfigs() {
  if (!fs.existsSync(CHARS_DIR)) {
    console.error(`Directory not found: ${CHARS_DIR}`)
    process.exit(1)
  }

  const dirs = fs.readdirSync(CHARS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort()
    .slice(0, MAX_CHARACTERS)

  const configs = {}
  const validKeys = []

  for (const dir of dirs) {
    const dirPath = path.join(CHARS_DIR, dir)
    const files = fs.readdirSync(dirPath).filter(f => f.endsWith('.fbx'))

    if (!files.includes('Idle.fbx')) {
      console.warn(`  [SKIP] ${dir} — no Idle.fbx`)
      continue
    }

    const key = sanitizeKey(dir)
    const basePath = `/models/Charecters/${dir}`

    const walkFile = findAnim(files, ANIM_MAP.walk)
    const runFile = findAnim(files, ANIM_MAP.run)
    const jumpFile = findAnim(files, ANIM_MAP.jump)

    const playerAnims = {
      idle: `${basePath}/Idle.fbx`,
    }
    if (walkFile) playerAnims.walk = `${basePath}/${walkFile}`
    if (runFile) playerAnims.run = `${basePath}/${runFile}`
    if (jumpFile) playerAnims.jump = `${basePath}/${jumpFile}`

    const height = HEIGHT_OVERRIDES[dir] || 1.8

    configs[key] = {
      displayName: dir,
      modelPath: `${basePath}/Idle.fbx`,
      playerAnims,
      height,
      systemPrompt: `You are ${dir}, a wizard at Hogwarts. Be friendly and talk about magic. Keep responses to 1-2 sentences.`,
    }

    validKeys.push(key)
  }

  // Generate NPC placements spread across the hall
  const placements = {}
  const count = validKeys.length
  for (let i = 0; i < count; i++) {
    const t = count > 1 ? i / (count - 1) : 0.5
    const z = HALL_Z[0] + t * (HALL_Z[1] - HALL_Z[0])
    const x = (i % 2 === 0 ? -1 : 1) * (3 + Math.random() * 8)
    const clampedX = Math.max(HALL_X[0], Math.min(HALL_X[1], x))
    placements[validKeys[i]] = {
      position: [parseFloat(clampedX.toFixed(1)), 0, parseFloat(z.toFixed(1))],
      rotation: parseFloat((Math.random() * Math.PI * 2 - Math.PI).toFixed(2)),
    }
  }

  // Generate groups (~4 NPCs per group)
  const groupCount = Math.max(3, Math.ceil(count / 4))
  const groups = {}
  for (let g = 0; g < groupCount; g++) {
    const t = groupCount > 1 ? g / (groupCount - 1) : 0.5
    const z = HALL_Z[0] + t * (HALL_Z[1] - HALL_Z[0])
    const x = (g % 2 === 0 ? 1 : -1) * 5
    const groupId = `group_${g + 1}`
    groups[groupId] = {
      meetingPoint: [x, 0, parseFloat(z.toFixed(1))],
      members: [],
    }
  }

  // Distribute NPCs round-robin into groups
  const groupIds = Object.keys(groups)
  for (let i = 0; i < validKeys.length; i++) {
    const gid = groupIds[i % groupIds.length]
    groups[gid].members.push(validKeys[i])
  }

  // Build output
  const output = `// AUTO-GENERATED by scripts/generateCharacterConfigs.js
// Do not edit manually — re-run: node scripts/generateCharacterConfigs.js

export const GENERATED_CHARACTERS = ${JSON.stringify(configs, null, 2)}

export const GENERATED_NPC_PLACEMENTS = ${JSON.stringify(placements, null, 2)}

export const GENERATED_NPC_GROUPS = ${JSON.stringify(groups, null, 2)}
`

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')
  console.log(`Generated ${validKeys.length} characters → ${OUTPUT_FILE}`)
  console.log(`Groups: ${groupCount} (${groupIds.join(', ')})`)
}

generateConfigs()
